// <auto-generated />
namespace _05_DataAnnotations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class OneToManyAuthorCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OneToManyAuthorCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202410080817394_OneToManyAuthorCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
